# Site settings
title: Irvington Math Club
description: > # this means to ignore newlines until "baseurl:"
  Website providing club materials and updates in a centralized location.
# baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-redirect-from

include:
  - _redirects
  - _pages

permalink: /:categories/:title

# comments
disqus: # add disqus shortname here

# author info
# add your appropriate info here
author: Irvington Math Club # your name
bio:    # your bio
email: irvingtonmathclub@gmail.com
email_md5: # md5 hash of your email
twitter_username:
github_username: irvington-math-club
facebook_username: groupsihsmathclub
instagram_username: ihsmath

# Theming options
# These settings are mandatory.
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'indigo-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'indigo-grey-200'
  color: 'indigo-grey-600'
